const handhelds = [
    {
        "NO": 1.0,
        "Brand": "ANBERNIC",
        "Model": "RG Cube",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 153.0,
        "Width": 86.0,
        "Tickness": 18.0,
        "Weight": 260.0,
        "Screen Size": 4.0,
        "Screen Resolution": "720*720",
        "Screen type": "LCD",
        "Battery": 5200.0,
        "Price": 160.0,
        "Chipset": "Unisoc T820",
        "Number of cores": "8",
        "RAM": 8.0,
        "Number of colors": 4.0,
        "Type": "Horizontal",
        "Year": 2024.0
    },
    {
        "NO": 2.0,
        "Brand": "ANBERNIC",
        "Model": "RG28XX",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 125.0,
        "Width": 57.0,
        "Tickness": 17.0,
        "Weight": 125.0,
        "Screen Size": 2.83,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3100.0,
        "Price": 50.0,
        "Chipset": " Cortex-A53",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 2024.0
    },
    {
        "NO": 3.0,
        "Brand": "ANBERNIC",
        "Model": "RG35XXSP",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 89.0,
        "Width": 85.0,
        "Tickness": 27.0,
        "Weight": 192.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3300.0,
        "Price": 70.0,
        "Chipset": " Cortex-A53",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Clamshell",
        "Year": 2024.0
    },
    {
        "NO": 4.0,
        "Brand": "ANBERNIC",
        "Model": "RG556",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 223.0,
        "Width": 90.0,
        "Tickness": 15.0,
        "Weight": 331.0,
        "Screen Size": 5.5,
        "Screen Resolution": "1920*1080",
        "Screen type": "LED",
        "Battery": 5500.0,
        "Price": 200.0,
        "Chipset": "Unisoc T820",
        "Number of cores": "8",
        "RAM": 8.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 5.0,
        "Brand": "ANBERNIC",
        "Model": "RG35XX H",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 145.0,
        "Width": 69.0,
        "Tickness": 16.0,
        "Weight": 180.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3300.0,
        "Price": 70.0,
        "Chipset": " Cortex-A53",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 6.0,
        "Brand": "ANBERNIC",
        "Model": "RG35XX Plus",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 117.0,
        "Width": 81.0,
        "Tickness": 22.0,
        "Weight": 186.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3300.0,
        "Price": 70.0,
        "Chipset": " Cortex-A53",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 7.0,
        "Brand": "ANBERNIC",
        "Model": "RG ARC-S",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 191.0,
        "Width": 80.0,
        "Tickness": 22.0,
        "Weight": 242.0,
        "Screen Size": 4.0,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3500.0,
        "Price": 90.0,
        "Chipset": " Cortex-A55",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 8.0,
        "Brand": "ANBERNIC",
        "Model": "RG ARC-D",
        "Material": "Plastic",
        "OS": "Linux-Android",
        "Length": 191.0,
        "Width": 80.0,
        "Tickness": 22.0,
        "Weight": 242.0,
        "Screen Size": 4.0,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3500.0,
        "Price": 110.0,
        "Chipset": " Cortex-A55",
        "Number of cores": "4",
        "RAM": 2.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 9.0,
        "Brand": "ANBERNIC",
        "Model": "RG405V",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 145.0,
        "Width": 105.0,
        "Tickness": 35.0,
        "Weight": 282.0,
        "Screen Size": 4.0,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 5500.0,
        "Price": 150.0,
        "Chipset": "Unisoc T618",
        "Number of cores": "8",
        "RAM": 4.0,
        "Number of colors": 3.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 10.0,
        "Brand": "ANBERNIC",
        "Model": "RG Nano",
        "Material": "Metal",
        "OS": "Linux",
        "Length": 71.0,
        "Width": 43.0,
        "Tickness": 17.0,
        "Weight": 75.0,
        "Screen Size": 1.54,
        "Screen Resolution": "240*240",
        "Screen type": "LCD",
        "Battery": 1050.0,
        "Price": 60.0,
        "Chipset": "Cortex-A7",
        "Number of cores": "",
        "RAM": 64.0,
        "Number of colors": 3.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 11.0,
        "Brand": "ANBERNIC",
        "Model": "RG353PS",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 174.0,
        "Width": 81.0,
        "Tickness": 20.0,
        "Weight": 213.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3500.0,
        "Price": 100.0,
        "Chipset": " Cortex-A55",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 12.0,
        "Brand": "ANBERNIC",
        "Model": "RG405M",
        "Material": "Metal",
        "OS": "Android",
        "Length": 163.0,
        "Width": 76.0,
        "Tickness": 16.0,
        "Weight": 260.0,
        "Screen Size": 4.0,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 4500.0,
        "Price": 180.0,
        "Chipset": "Unisoc T618",
        "Number of cores": "8",
        "RAM": 4.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 13.0,
        "Brand": "ANBERNIC",
        "Model": "RG35XX ",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 117.0,
        "Width": 81.0,
        "Tickness": 20.0,
        "Weight": 165.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 2600.0,
        "Price": 50.0,
        "Chipset": "Cortex-A9",
        "Number of cores": "4",
        "RAM": 256.0,
        "Number of colors": 3.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 14.0,
        "Brand": "ANBERNIC",
        "Model": "RG505",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 189.0,
        "Width": 87.0,
        "Tickness": 18.0,
        "Weight": 286.0,
        "Screen Size": 5.0,
        "Screen Resolution": "960*544",
        "Screen type": "LED",
        "Battery": 5000.0,
        "Price": 150.0,
        "Chipset": "Unisoc T618",
        "Number of cores": "8",
        "RAM": 4.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 15.0,
        "Brand": "ANBERNIC",
        "Model": "RG353M",
        "Material": "Metal",
        "OS": "Linux-Android",
        "Length": 145.0,
        "Width": 70.0,
        "Tickness": 16.0,
        "Weight": 232.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3500.0,
        "Price": 150.0,
        "Chipset": " Cortex-A55",
        "Number of cores": "4",
        "RAM": 2.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 16.0,
        "Brand": "ANBERNIC",
        "Model": "RG353V",
        "Material": "Plastic",
        "OS": "Linux-Android",
        "Length": 126.0,
        "Width": 83.0,
        "Tickness": 21.0,
        "Weight": 180.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3200.0,
        "Price": 120.0,
        "Chipset": " Cortex-A55",
        "Number of cores": "4",
        "RAM": 2.0,
        "Number of colors": 4.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 17.0,
        "Brand": "ANBERNIC",
        "Model": "RG353VS",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 126.0,
        "Width": 83.0,
        "Tickness": 21.0,
        "Weight": 180.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3200.0,
        "Price": 100.0,
        "Chipset": " Cortex-A55",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 2.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 18.0,
        "Brand": "ANBERNIC",
        "Model": "WIN600",
        "Material": "Plastic",
        "OS": "Windows",
        "Length": 236.0,
        "Width": 103.0,
        "Tickness": 22.0,
        "Weight": 490.0,
        "Screen Size": 6.0,
        "Screen Resolution": "1280*720",
        "Screen type": "LCD",
        "Battery": 4500.0,
        "Price": 300.0,
        "Chipset": "AMD 3050e",
        "Number of cores": "",
        "RAM": 8.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 19.0,
        "Brand": "ANBERNIC",
        "Model": "RG353P",
        "Material": "Plastic",
        "OS": "Linux-Android",
        "Length": 201.0,
        "Width": 100.0,
        "Tickness": 47.0,
        "Weight": 422.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3500.0,
        "Price": 120.0,
        "Chipset": " Cortex-A55",
        "Number of cores": "4",
        "RAM": 2.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 20.0,
        "Brand": "ANBERNIC",
        "Model": "RG503",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 190.0,
        "Width": 84.0,
        "Tickness": 21.0,
        "Weight": 230.0,
        "Screen Size": 5.0,
        "Screen Resolution": "960*544",
        "Screen type": "LED",
        "Battery": 3500.0,
        "Price": 150.0,
        "Chipset": " Cortex-A55",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 21.0,
        "Brand": "ANBERNIC",
        "Model": "RG552",
        "Material": "Plastic",
        "OS": "Linux-Android",
        "Length": 200.0,
        "Width": 85.0,
        "Tickness": 20.0,
        "Weight": 367.0,
        "Screen Size": 5.36,
        "Screen Resolution": "1920 * 1152",
        "Screen type": "LCD",
        "Battery": 6400.0,
        "Price": 190.0,
        "Chipset": "A72\u00d72 + A53\u00d74",
        "Number of cores": "6",
        "RAM": 4.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 22.0,
        "Brand": "ANBERNIC",
        "Model": "Retro Game Plus",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 146.0,
        "Width": 66.0,
        "Tickness": 21.0,
        "Weight": 140.0,
        "Screen Size": 3.0,
        "Screen Resolution": "960*480",
        "Screen type": "LCD",
        "Battery": 1800.0,
        "Price": 50.0,
        "Chipset": "",
        "Number of cores": "2",
        "RAM": 128.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 23.0,
        "Brand": "ANBERNIC",
        "Model": "RG351MP",
        "Material": "Metal",
        "OS": "Linux",
        "Length": 145.0,
        "Width": 73.0,
        "Tickness": 18.0,
        "Weight": 267.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3500.0,
        "Price": 150.0,
        "Chipset": "RK3326",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 24.0,
        "Brand": "ANBERNIC",
        "Model": "PAP KIII",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 170.0,
        "Width": 76.0,
        "Tickness": 16.0,
        "Weight": 162.0,
        "Screen Size": 4.3,
        "Screen Resolution": "\u00a0480*272",
        "Screen type": "LCD",
        "Battery": 1000.0,
        "Price": 55.0,
        "Chipset": "JZ4760",
        "Number of cores": "",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 25.0,
        "Brand": "ANBERNIC",
        "Model": "RG350",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 145.0,
        "Width": 83.0,
        "Tickness": 14.0,
        "Weight": 160.0,
        "Screen Size": 3.5,
        "Screen Resolution": "320*240",
        "Screen type": "LCD",
        "Battery": 2500.0,
        "Price": 80.0,
        "Chipset": "JZ4770",
        "Number of cores": "2",
        "RAM": 512.0,
        "Number of colors": 4.0,
        "Type": "Horizontal",
        "Year": 2019.0
    },
    {
        "NO": 26.0,
        "Brand": "ANBERNIC",
        "Model": "RG350M",
        "Material": "Metal",
        "OS": "Linux",
        "Length": 145.0,
        "Width": 83.0,
        "Tickness": 18.0,
        "Weight": 250.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 2500.0,
        "Price": 110.0,
        "Chipset": "JZ4770",
        "Number of cores": "2",
        "RAM": 512.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 2020.0
    },
    {
        "NO": 27.0,
        "Brand": "ANBERNIC",
        "Model": "RG280M",
        "Material": "Metal",
        "OS": "Linux",
        "Length": 136.0,
        "Width": 61.0,
        "Tickness": 18.0,
        "Weight": 205.0,
        "Screen Size": 2.8,
        "Screen Resolution": "320*240",
        "Screen type": "LCD",
        "Battery": 2500.0,
        "Price": 85.0,
        "Chipset": "JZ4770",
        "Number of cores": "2",
        "RAM": 512.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 2020.0
    },
    {
        "NO": 28.0,
        "Brand": "ANBERNIC",
        "Model": "RG350P",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 145.0,
        "Width": 73.0,
        "Tickness": 18.0,
        "Weight": 176.0,
        "Screen Size": 3.5,
        "Screen Resolution": "320*240",
        "Screen type": "LCD",
        "Battery": 2500.0,
        "Price": 80.0,
        "Chipset": "JZ4770",
        "Number of cores": "2",
        "RAM": 512.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 2020.0
    },
    {
        "NO": 29.0,
        "Brand": "ANBERNIC",
        "Model": "K101 Plus",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 145.0,
        "Width": 65.0,
        "Tickness": 19.0,
        "Weight": 143.0,
        "Screen Size": 3.0,
        "Screen Resolution": "320*240",
        "Screen type": "LCD",
        "Battery": 800.0,
        "Price": 75.0,
        "Chipset": "ARM7+ARM9",
        "Number of cores": "2",
        "RAM": 0.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 30.0,
        "Brand": "ANBERNIC",
        "Model": "RG351P",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 156.0,
        "Width": 71.0,
        "Tickness": 18.0,
        "Weight": 160.0,
        "Screen Size": 3.5,
        "Screen Resolution": "320*480",
        "Screen type": "LCD",
        "Battery": 3500.0,
        "Price": 90.0,
        "Chipset": "RK3326",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 31.0,
        "Brand": "ANBERNIC",
        "Model": "RG280V",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 89.0,
        "Width": 78.0,
        "Tickness": 18.0,
        "Weight": 240.0,
        "Screen Size": 2.8,
        "Screen Resolution": "320*480",
        "Screen type": "LCD",
        "Battery": 2100.0,
        "Price": 80.0,
        "Chipset": "JZ4770",
        "Number of cores": "2",
        "RAM": 512.0,
        "Number of colors": 2.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 32.0,
        "Brand": "ANBERNIC",
        "Model": "RG351M",
        "Material": "Metal",
        "OS": "Linux",
        "Length": 156.0,
        "Width": 71.0,
        "Tickness": 18.0,
        "Weight": 260.0,
        "Screen Size": 3.5,
        "Screen Resolution": "320*480",
        "Screen type": "LCD",
        "Battery": 3500.0,
        "Price": 130.0,
        "Chipset": "RK3326",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 33.0,
        "Brand": "ANBERNIC",
        "Model": "RG351V",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 140.0,
        "Width": 94.0,
        "Tickness": 29.0,
        "Weight": 200.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3900.0,
        "Price": 90.0,
        "Chipset": "RK3326",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 34.0,
        "Brand": "ANBERNIC",
        "Model": "RG300X",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 137.0,
        "Width": 69.0,
        "Tickness": 20.0,
        "Weight": 160.0,
        "Screen Size": 3.0,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 2500.0,
        "Price": 70.0,
        "Chipset": "JZ4770",
        "Number of cores": "2",
        "RAM": 512.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 35.0,
        "Brand": "POWKIDDY",
        "Model": "Q90",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 135.0,
        "Width": 71.0,
        "Tickness": 15.0,
        "Weight": 100.0,
        "Screen Size": 3.0,
        "Screen Resolution": "320x240",
        "Screen type": "LCD",
        "Battery": 600.0,
        "Price": 30.0,
        "Chipset": "RK3326",
        "Number of cores": "4",
        "RAM": 512.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 2019.0
    },
    {
        "NO": 37.0,
        "Brand": "POWKIDDY",
        "Model": "RGB10M",
        "Material": "Metal",
        "OS": "Linux",
        "Length": 144.0,
        "Width": 63.0,
        "Tickness": 16.0,
        "Weight": 215.0,
        "Screen Size": 3.5,
        "Screen Resolution": "480*320",
        "Screen type": "LCD",
        "Battery": 3500.0,
        "Price": 120.0,
        "Chipset": "RK3326",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 2021.0
    },
    {
        "NO": 38.0,
        "Brand": "POWKIDDY",
        "Model": "RGB20S",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 120.0,
        "Width": 83.0,
        "Tickness": 21.0,
        "Weight": 240.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3500.0,
        "Price": 70.0,
        "Chipset": "RK3326",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 5.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 39.0,
        "Brand": "POWKIDDY",
        "Model": "RGB30",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 145.0,
        "Width": 86.0,
        "Tickness": 18.0,
        "Weight": 207.0,
        "Screen Size": 4.0,
        "Screen Resolution": "720*720",
        "Screen type": "LCD",
        "Battery": 4100.0,
        "Price": 90.0,
        "Chipset": "RK3566",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 6.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 40.0,
        "Brand": "POWKIDDY",
        "Model": "RGB20SX",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 143.0,
        "Width": 87.0,
        "Tickness": 22.0,
        "Weight": 0.0,
        "Screen Size": 4.0,
        "Screen Resolution": "720*720",
        "Screen type": "LCD",
        "Battery": 5000.0,
        "Price": 90.0,
        "Chipset": "RK3566",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 5.0,
        "Type": "Vertical",
        "Year": 2024.0
    },
    {
        "NO": 41.0,
        "Brand": "POWKIDDY",
        "Model": "X55",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 212.0,
        "Width": 94.0,
        "Tickness": 19.0,
        "Weight": 293.0,
        "Screen Size": 5.5,
        "Screen Resolution": "1280*720",
        "Screen type": "LCD",
        "Battery": 4000.0,
        "Price": 100.0,
        "Chipset": "RK3566",
        "Number of cores": "4",
        "RAM": 2.0,
        "Number of colors": 4.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 42.0,
        "Brand": "POWKIDDY",
        "Model": "RGB10MAX3",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 189.0,
        "Width": 76.0,
        "Tickness": 18.0,
        "Weight": 215.0,
        "Screen Size": 5.0,
        "Screen Resolution": "1280*720",
        "Screen type": "LCD",
        "Battery": 4000.0,
        "Price": 100.0,
        "Chipset": "RK3566",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 6.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 43.0,
        "Brand": "POWKIDDY",
        "Model": "RGB10MAX3 PRO",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 183.0,
        "Width": 84.0,
        "Tickness": 18.0,
        "Weight": 254.0,
        "Screen Size": 5.0,
        "Screen Resolution": "854*480",
        "Screen type": "LCD",
        "Battery": 4000.0,
        "Price": 120.0,
        "Chipset": "A311D",
        "Number of cores": "6",
        "RAM": 2.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 44.0,
        "Brand": "POWKIDDY",
        "Model": "X70",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 236.0,
        "Width": 117.0,
        "Tickness": 14.0,
        "Weight": 358.0,
        "Screen Size": 7.0,
        "Screen Resolution": "1024*600",
        "Screen type": "LCD",
        "Battery": 3500.0,
        "Price": 60.0,
        "Chipset": "ATM7051",
        "Number of cores": "4",
        "RAM": 128.0,
        "Number of colors": 4.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 45.0,
        "Brand": "POWKIDDY",
        "Model": "X28",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 208.0,
        "Width": 81.0,
        "Tickness": 27.0,
        "Weight": 400.0,
        "Screen Size": 5.5,
        "Screen Resolution": "1280*720",
        "Screen type": "LCD",
        "Battery": 5000.0,
        "Price": 130.0,
        "Chipset": "T618",
        "Number of cores": "8",
        "RAM": 4.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 46.0,
        "Brand": "POWKIDDY",
        "Model": "V90",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 80.0,
        "Width": 78.0,
        "Tickness": 24.0,
        "Weight": 120.0,
        "Screen Size": 3.0,
        "Screen Resolution": "320x240",
        "Screen type": "LCD",
        "Battery": 1000.0,
        "Price": 50.0,
        "Chipset": "ARM9",
        "Number of cores": "",
        "RAM": 0.0,
        "Number of colors": 3.0,
        "Type": "Clamshell",
        "Year": 0.0
    },
    {
        "NO": 47.0,
        "Brand": "POWKIDDY",
        "Model": "MIYOO Mini Plus",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 108.0,
        "Width": 78.0,
        "Tickness": 22.0,
        "Weight": 162.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3000.0,
        "Price": 70.0,
        "Chipset": "Cortex-A7",
        "Number of cores": "2",
        "RAM": 0.0,
        "Number of colors": 4.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 48.0,
        "Brand": "POWKIDDY",
        "Model": "RK2023",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 151.0,
        "Width": 78.0,
        "Tickness": 17.0,
        "Weight": 180.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3500.0,
        "Price": 80.0,
        "Chipset": "RK3566",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 2023.0
    },
    {
        "NO": 49.0,
        "Brand": "POWKIDDY",
        "Model": "RGB10MAX",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 185.0,
        "Width": 75.0,
        "Tickness": 18.0,
        "Weight": 215.0,
        "Screen Size": 5.0,
        "Screen Resolution": "854*480",
        "Screen type": "LCD",
        "Battery": 4200.0,
        "Price": 90.0,
        "Chipset": "RK3326",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 50.0,
        "Brand": "POWKIDDY",
        "Model": "X18S",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 210.0,
        "Width": 120.0,
        "Tickness": 35.0,
        "Weight": 310.0,
        "Screen Size": 5.5,
        "Screen Resolution": "1280*720",
        "Screen type": "LCD",
        "Battery": 5000.0,
        "Price": 120.0,
        "Chipset": "T618",
        "Number of cores": "8",
        "RAM": 4.0,
        "Number of colors": 2.0,
        "Type": "Clamshell",
        "Year": 0.0
    },
    {
        "NO": 51.0,
        "Brand": "POWKIDDY",
        "Model": "Q36 Mini",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 94.0,
        "Width": 43.0,
        "Tickness": 16.0,
        "Weight": 54.0,
        "Screen Size": 1.54,
        "Screen Resolution": "240*240",
        "Screen type": "LCD",
        "Battery": 1000.0,
        "Price": 60.0,
        "Chipset": "Corte-A7",
        "Number of cores": "",
        "RAM": 0.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 52.0,
        "Brand": "POWKIDDY",
        "Model": "A20",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 140.0,
        "Width": 85.0,
        "Tickness": 20.0,
        "Weight": 0.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 3000.0,
        "Price": 110.0,
        "Chipset": "S905D3",
        "Number of cores": "4",
        "RAM": 2.0,
        "Number of colors": 1.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 53.0,
        "Brand": "POWKIDDY",
        "Model": "Trimui Smart Pro",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 180.0,
        "Width": 80.0,
        "Tickness": 17.0,
        "Weight": 311.0,
        "Screen Size": 5.0,
        "Screen Resolution": "1280*720",
        "Screen type": "LCD",
        "Battery": 5000.0,
        "Price": 100.0,
        "Chipset": "A133P",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 54.0,
        "Brand": "POWKIDDY",
        "Model": "Q20 MINI",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 118.0,
        "Width": 55.0,
        "Tickness": 15.0,
        "Weight": 80.0,
        "Screen Size": 2.4,
        "Screen Resolution": "320x240",
        "Screen type": "LCD",
        "Battery": 1200.0,
        "Price": 40.0,
        "Chipset": "ARM9",
        "Number of cores": "",
        "RAM": 0.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 55.0,
        "Brand": "POWKIDDY",
        "Model": "Magicx XU10",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 0.0,
        "Width": 0.0,
        "Tickness": 22.0,
        "Weight": 0.0,
        "Screen Size": 3.5,
        "Screen Resolution": "854*480",
        "Screen type": "LCD",
        "Battery": 3000.0,
        "Price": 70.0,
        "Chipset": "RK3326",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 3.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 56.0,
        "Brand": "POWKIDDY",
        "Model": "X39pro",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 170.0,
        "Width": 72.0,
        "Tickness": 18.0,
        "Weight": 350.0,
        "Screen Size": 4.3,
        "Screen Resolution": "480*272",
        "Screen type": "LCD",
        "Battery": 2500.0,
        "Price": 50.0,
        "Chipset": "ATM7051",
        "Number of cores": "4",
        "RAM": 128.0,
        "Number of colors": 1.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 57.0,
        "Brand": "POWKIDDY",
        "Model": "X17",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 255.0,
        "Width": 130.0,
        "Tickness": 45.0,
        "Weight": 400.0,
        "Screen Size": 7.0,
        "Screen Resolution": "1024*600",
        "Screen type": "LCD",
        "Battery": 4000.0,
        "Price": 100.0,
        "Chipset": "A53",
        "Number of cores": "4",
        "RAM": 2.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 58.0,
        "Brand": "POWKIDDY",
        "Model": "RGB10S",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 144.0,
        "Width": 64.0,
        "Tickness": 16.0,
        "Weight": 140.0,
        "Screen Size": 3.5,
        "Screen Resolution": "480*320",
        "Screen type": "LCD",
        "Battery": 3000.0,
        "Price": 90.0,
        "Chipset": "RK3326",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 59.0,
        "Brand": "POWKIDDY",
        "Model": "X51",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 189.0,
        "Width": 93.0,
        "Tickness": 18.0,
        "Weight": 254.0,
        "Screen Size": 5.0,
        "Screen Resolution": "800*480",
        "Screen type": "LCD",
        "Battery": 2500.0,
        "Price": 50.0,
        "Chipset": "ATM7051",
        "Number of cores": "4",
        "RAM": 128.0,
        "Number of colors": 4.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 60.0,
        "Brand": "POWKIDDY",
        "Model": "Trimui",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 110.0,
        "Width": 58.0,
        "Tickness": 15.0,
        "Weight": 100.0,
        "Screen Size": 2.4,
        "Screen Resolution": "320*240",
        "Screen type": "LCD",
        "Battery": 1000.0,
        "Price": 60.0,
        "Chipset": "",
        "Number of cores": "",
        "RAM": 128.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 61.0,
        "Brand": "POWKIDDY",
        "Model": "RGB20",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 108.0,
        "Width": 93.0,
        "Tickness": 20.0,
        "Weight": 171.0,
        "Screen Size": 3.5,
        "Screen Resolution": "480*320",
        "Screen type": "LCD",
        "Battery": 3000.0,
        "Price": 90.0,
        "Chipset": "RK3326",
        "Number of cores": "4",
        "RAM": 1.0,
        "Number of colors": 2.0,
        "Type": "Vertical",
        "Year": 0.0
    },
    {
        "NO": 62.0,
        "Brand": "POWKIDDY",
        "Model": "X18",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 210.0,
        "Width": 120.0,
        "Tickness": 35.0,
        "Weight": 300.0,
        "Screen Size": 5.5,
        "Screen Resolution": "1280*720",
        "Screen type": "LCD",
        "Battery": 5000.0,
        "Price": 100.0,
        "Chipset": "\u00a0MTK 8163",
        "Number of cores": "4",
        "RAM": 2.0,
        "Number of colors": 1.0,
        "Type": "Clamshell",
        "Year": 0.0
    },
    {
        "NO": 63.0,
        "Brand": "RETROID",
        "Model": "Pocket 4",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 185.0,
        "Width": 83.0,
        "Tickness": 16.0,
        "Weight": 261.0,
        "Screen Size": 4.7,
        "Screen Resolution": "750*1334",
        "Screen type": "LCD",
        "Battery": 5000.0,
        "Price": 200.0,
        "Chipset": "A78+A55",
        "Number of cores": "8",
        "RAM": 4.0,
        "Number of colors": 6.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 64.0,
        "Brand": "RETROID",
        "Model": "Pocket 4Pro",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 185.0,
        "Width": 83.0,
        "Tickness": 16.0,
        "Weight": 261.0,
        "Screen Size": 4.7,
        "Screen Resolution": "750*1334",
        "Screen type": "LCD",
        "Battery": 5000.0,
        "Price": 200.0,
        "Chipset": "A78+A55",
        "Number of cores": "8",
        "RAM": 8.0,
        "Number of colors": 6.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 65.0,
        "Brand": "RETROID",
        "Model": "Pocket 2S",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 155.0,
        "Width": 81.0,
        "Tickness": 28.0,
        "Weight": 200.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 4000.0,
        "Price": 100.0,
        "Chipset": "A75+A55",
        "Number of cores": "8",
        "RAM": 4.0,
        "Number of colors": 6.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 66.0,
        "Brand": "RETROID",
        "Model": "Pocket 2S Metal",
        "Material": "Metal",
        "OS": "Android",
        "Length": 155.0,
        "Width": 81.0,
        "Tickness": 28.0,
        "Weight": 254.0,
        "Screen Size": 3.5,
        "Screen Resolution": "640*480",
        "Screen type": "LCD",
        "Battery": 4000.0,
        "Price": 150.0,
        "Chipset": "A75+A55",
        "Number of cores": "8",
        "RAM": 4.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 67.0,
        "Brand": "RETROID",
        "Model": "Pocket 3+",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 185.0,
        "Width": 81.0,
        "Tickness": 24.0,
        "Weight": 235.0,
        "Screen Size": 4.7,
        "Screen Resolution": "750*1334",
        "Screen type": "LCD",
        "Battery": 4500.0,
        "Price": 130.0,
        "Chipset": "T618",
        "Number of cores": "8",
        "RAM": 4.0,
        "Number of colors": 8.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 68.0,
        "Brand": "AYN",
        "Model": "Odin ",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 224.0,
        "Width": 95.0,
        "Tickness": 15.0,
        "Weight": 365.0,
        "Screen Size": 6.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 6600.0,
        "Price": 200.0,
        "Chipset": "SD845",
        "Number of cores": "8",
        "RAM": 4.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 69.0,
        "Brand": "AYN",
        "Model": "Odin Lite",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 224.0,
        "Width": 95.0,
        "Tickness": 15.0,
        "Weight": 365.0,
        "Screen Size": 6.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 6600.0,
        "Price": 200.0,
        "Chipset": "D900",
        "Number of cores": "8",
        "RAM": 4.0,
        "Number of colors": 4.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 70.0,
        "Brand": "AYN",
        "Model": "Odin Pro",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 224.0,
        "Width": 95.0,
        "Tickness": 15.0,
        "Weight": 365.0,
        "Screen Size": 6.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 6600.0,
        "Price": 250.0,
        "Chipset": "SD845",
        "Number of cores": "8",
        "RAM": 8.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 71.0,
        "Brand": "AYN",
        "Model": "Odin 2",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 225.0,
        "Width": 98.0,
        "Tickness": 17.0,
        "Weight": 420.0,
        "Screen Size": 6.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 8000.0,
        "Price": 300.0,
        "Chipset": "SD8 Gen2",
        "Number of cores": "8",
        "RAM": 8.0,
        "Number of colors": 6.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 72.0,
        "Brand": "AYN",
        "Model": "Odin 2 Pro",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 225.0,
        "Width": 98.0,
        "Tickness": 17.0,
        "Weight": 420.0,
        "Screen Size": 6.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 8000.0,
        "Price": 370.0,
        "Chipset": "SD8 Gen2",
        "Number of cores": "8",
        "RAM": 12.0,
        "Number of colors": 6.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 73.0,
        "Brand": "AYN",
        "Model": "Odin 2 Max",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 225.0,
        "Width": 98.0,
        "Tickness": 17.0,
        "Weight": 420.0,
        "Screen Size": 6.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 8000.0,
        "Price": 460.0,
        "Chipset": "SD8 Gen2",
        "Number of cores": "8",
        "RAM": 16.0,
        "Number of colors": 6.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 74.0,
        "Brand": "AYN",
        "Model": "Loki ",
        "Material": "Plastic",
        "OS": "Windows",
        "Length": 248.0,
        "Width": 96.0,
        "Tickness": 35.0,
        "Weight": 570.0,
        "Screen Size": 6.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 0.0,
        "Price": 420.0,
        "Chipset": "AMD 6600U",
        "Number of cores": "6",
        "RAM": 16.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 75.0,
        "Brand": "AYN",
        "Model": "Loki Zero",
        "Material": "Plastic",
        "OS": "Windows",
        "Length": 248.0,
        "Width": 96.0,
        "Tickness": 35.0,
        "Weight": 570.0,
        "Screen Size": 6.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 0.0,
        "Price": 250.0,
        "Chipset": "3050e",
        "Number of cores": "",
        "RAM": 4.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 76.0,
        "Brand": "AYN",
        "Model": "Loki Max",
        "Material": "Plastic",
        "OS": "Windows",
        "Length": 248.0,
        "Width": 96.0,
        "Tickness": 35.0,
        "Weight": 570.0,
        "Screen Size": 6.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 0.0,
        "Price": 450.0,
        "Chipset": "AMD 6800U",
        "Number of cores": "12",
        "RAM": 16.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 77.0,
        "Brand": "AYN",
        "Model": "Odin 2 mini ",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 198.0,
        "Width": 86.0,
        "Tickness": 20.0,
        "Weight": 320.0,
        "Screen Size": 5.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LED",
        "Battery": 5000.0,
        "Price": 330.0,
        "Chipset": "SD8 Gen2",
        "Number of cores": "8",
        "RAM": 8.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 2024.0
    },
    {
        "NO": 78.0,
        "Brand": "AYN",
        "Model": "Odin 2 mini Pro",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 198.0,
        "Width": 86.0,
        "Tickness": 20.0,
        "Weight": 320.0,
        "Screen Size": 5.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LED",
        "Battery": 5000.0,
        "Price": 400.0,
        "Chipset": "SD8 Gen2",
        "Number of cores": "8",
        "RAM": 12.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 2024.0
    },
    {
        "NO": 79.0,
        "Brand": "LOGITECH",
        "Model": "Cloud",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 257.0,
        "Width": 117.0,
        "Tickness": 33.0,
        "Weight": 463.0,
        "Screen Size": 7.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 6000.0,
        "Price": 330.0,
        "Chipset": "SD720G",
        "Number of cores": "8",
        "RAM": 4.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 80.0,
        "Brand": "STEAM",
        "Model": "Steam Deck",
        "Material": "Plastic",
        "OS": "SteamOS",
        "Length": 298.0,
        "Width": 117.0,
        "Tickness": 49.0,
        "Weight": 669.0,
        "Screen Size": 7.0,
        "Screen Resolution": "1280*800",
        "Screen type": "LCD",
        "Battery": 0.0,
        "Price": 350.0,
        "Chipset": "",
        "Number of cores": "",
        "RAM": 16.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 81.0,
        "Brand": "STEAM",
        "Model": "Steam Deck LED",
        "Material": "Plastic",
        "OS": "SteamOS",
        "Length": 298.0,
        "Width": 117.0,
        "Tickness": 49.0,
        "Weight": 640.0,
        "Screen Size": 7.4,
        "Screen Resolution": "1280*800",
        "Screen type": "LED",
        "Battery": 0.0,
        "Price": 480.0,
        "Chipset": "",
        "Number of cores": "",
        "RAM": 16.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 82.0,
        "Brand": "STEAM",
        "Model": "Steam Deck LED 1T",
        "Material": "Plastic",
        "OS": "SteamOS",
        "Length": 298.0,
        "Width": 117.0,
        "Tickness": 49.0,
        "Weight": 640.0,
        "Screen Size": 7.4,
        "Screen Resolution": "1280*800",
        "Screen type": "LED",
        "Battery": 0.0,
        "Price": 570.0,
        "Chipset": "",
        "Number of cores": "",
        "RAM": 16.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 83.0,
        "Brand": "ONEXPLAYER",
        "Model": "MINI PRO",
        "Material": "Plastic",
        "OS": "Windows",
        "Length": 260.0,
        "Width": 106.0,
        "Tickness": 23.0,
        "Weight": 619.0,
        "Screen Size": 7.0,
        "Screen Resolution": "1280*800",
        "Screen type": "LCD",
        "Battery": 0.0,
        "Price": 400.0,
        "Chipset": "Intel 8505",
        "Number of cores": "",
        "RAM": 16.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 84.0,
        "Brand": "EVERCADE",
        "Model": "EXP",
        "Material": "Plastic",
        "OS": "Linux",
        "Length": 193.0,
        "Width": 78.0,
        "Tickness": 21.0,
        "Weight": 270.0,
        "Screen Size": 4.3,
        "Screen Resolution": "800*480",
        "Screen type": "LCD",
        "Battery": 3000.0,
        "Price": 150.0,
        "Chipset": "",
        "Number of cores": "",
        "RAM": 0.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 85.0,
        "Brand": "NINTENDO",
        "Model": "Switch",
        "Material": "Plastic",
        "OS": "Horizon",
        "Length": 239.0,
        "Width": 102.0,
        "Tickness": 14.0,
        "Weight": 400.0,
        "Screen Size": 7.0,
        "Screen Resolution": "1280*800",
        "Screen type": "LCD",
        "Battery": 4310.0,
        "Price": 260.0,
        "Chipset": "",
        "Number of cores": "",
        "RAM": 0.0,
        "Number of colors": 0.0,
        "Type": "Detachable",
        "Year": 0.0
    },
    {
        "NO": 86.0,
        "Brand": "NINTENDO",
        "Model": "Switch LED",
        "Material": "Plastic",
        "OS": "Horizon",
        "Length": 239.0,
        "Width": 102.0,
        "Tickness": 14.0,
        "Weight": 400.0,
        "Screen Size": 7.0,
        "Screen Resolution": "1280*800",
        "Screen type": "LED",
        "Battery": 4310.0,
        "Price": 300.0,
        "Chipset": "",
        "Number of cores": "",
        "RAM": 0.0,
        "Number of colors": 0.0,
        "Type": "Detachable",
        "Year": 0.0
    },
    {
        "NO": 87.0,
        "Brand": "NINTENDO",
        "Model": "Switch Lite",
        "Material": "Plastic",
        "OS": "Horizon",
        "Length": 208.0,
        "Width": 91.0,
        "Tickness": 14.0,
        "Weight": 276.0,
        "Screen Size": 5.5,
        "Screen Resolution": "1280*800",
        "Screen type": "LCD",
        "Battery": 3570.0,
        "Price": 200.0,
        "Chipset": "",
        "Number of cores": "",
        "RAM": 0.0,
        "Number of colors": 5.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 88.0,
        "Brand": "PIMAX",
        "Model": "Portal Retro",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 225.0,
        "Width": 89.0,
        "Tickness": 14.0,
        "Weight": 306.0,
        "Screen Size": 5.5,
        "Screen Resolution": "2560*1440",
        "Screen type": "LCD",
        "Battery": 4000.0,
        "Price": 200.0,
        "Chipset": "",
        "Number of cores": "",
        "RAM": 8.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 89.0,
        "Brand": "PIMAX",
        "Model": "Poratal",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 225.0,
        "Width": 89.0,
        "Tickness": 14.0,
        "Weight": 367.0,
        "Screen Size": 5.5,
        "Screen Resolution": "3840*2160",
        "Screen type": "LCD",
        "Battery": 4000.0,
        "Price": 300.0,
        "Chipset": "",
        "Number of cores": "",
        "RAM": 8.0,
        "Number of colors": 0.0,
        "Type": "Detachable",
        "Year": 0.0
    },
    {
        "NO": 90.0,
        "Brand": "AYANEO",
        "Model": "Next Lite",
        "Material": "Plastic",
        "OS": "Windows",
        "Length": 267.0,
        "Width": 112.0,
        "Tickness": 22.0,
        "Weight": 720.0,
        "Screen Size": 7.0,
        "Screen Resolution": "1280*800",
        "Screen type": "LCD",
        "Battery": 0.0,
        "Price": 350.0,
        "Chipset": "AMD",
        "Number of cores": "",
        "RAM": 16.0,
        "Number of colors": 3.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 91.0,
        "Brand": "AYANEO",
        "Model": "Pocket AIR",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 224.0,
        "Width": 89.0,
        "Tickness": 17.0,
        "Weight": 380.0,
        "Screen Size": 5.5,
        "Screen Resolution": "1920*1080",
        "Screen type": "LED",
        "Battery": 0.0,
        "Price": 300.0,
        "Chipset": "Dimensity 1200",
        "Number of cores": "8",
        "RAM": 6.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 92.0,
        "Brand": "AYANEO",
        "Model": "Pocket S",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 214.0,
        "Width": 85.0,
        "Tickness": 14.0,
        "Weight": 358.0,
        "Screen Size": 6.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 6000.0,
        "Price": 500.0,
        "Chipset": "SD8 Gen2",
        "Number of cores": "8",
        "RAM": 12.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 2024.0
    },
    {
        "NO": 93.0,
        "Brand": "Lenovo ",
        "Model": "Legion Go",
        "Material": "Plastic",
        "OS": "Windows",
        "Length": 299.0,
        "Width": 131.0,
        "Tickness": 41.0,
        "Weight": 854.0,
        "Screen Size": 8.8,
        "Screen Resolution": "2560*1600",
        "Screen type": "LCD",
        "Battery": 0.0,
        "Price": 700.0,
        "Chipset": "AMD Z1",
        "Number of cores": "14",
        "RAM": 16.0,
        "Number of colors": 1.0,
        "Type": "Detachable",
        "Year": 0.0
    },
    {
        "NO": 94.0,
        "Brand": "Asus",
        "Model": "Rog Ally",
        "Material": "Plastic",
        "OS": "Windows",
        "Length": 280.0,
        "Width": 111.0,
        "Tickness": 21.0,
        "Weight": 608.0,
        "Screen Size": 7.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 0.0,
        "Price": 600.0,
        "Chipset": "AMD Z1",
        "Number of cores": "8+G1H88:P110",
        "RAM": 16.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 2023.0
    },
    {
        "NO": 95.0,
        "Brand": "abxylute",
        "Model": "abxylute",
        "Material": "Plastic",
        "OS": "Android",
        "Length": 250.0,
        "Width": 115.0,
        "Tickness": 30.0,
        "Weight": 430.0,
        "Screen Size": 7.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 5200.0,
        "Price": 170.0,
        "Chipset": "MT8365",
        "Number of cores": "4",
        "RAM": 4.0,
        "Number of colors": 2.0,
        "Type": "Horizontal",
        "Year": 0.0
    },
    {
        "NO": 96.0,
        "Brand": "MSI",
        "Model": "Claw A1M",
        "Material": "Plastic",
        "OS": "Windows",
        "Length": 294.0,
        "Width": 117.0,
        "Tickness": 21.0,
        "Weight": 675.0,
        "Screen Size": 7.0,
        "Screen Resolution": "1920*1080",
        "Screen type": "LCD",
        "Battery": 0.0,
        "Price": 700.0,
        "Chipset": "Intel",
        "Number of cores": "",
        "RAM": 0.0,
        "Number of colors": 1.0,
        "Type": "Horizontal",
        "Year": 0.0
    }
];